using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

//class to calculate the delivery cost
namespace GroceerLKS
{   
    //generated by chatGPT
    public class Delivery
    {
        private const decimal EarthRadius = 6371m; // Radius bumi dalam km
        private const decimal CostPer100Km = 15000m; // Biaya per 100 km

        // Fungsi untuk mengubah derajat ke radian dalam decimal
        private static decimal ToRadians(decimal angle)
        {
            return angle * (decimal)Math.PI / 180m;
        }

        // Fungsi untuk menghitung jarak menggunakan Haversine Formula
        private static decimal CalculateDistance(decimal latitudeCustomer, decimal longitudeCustomer, decimal latitudeVendor, decimal longitudeVendor)
        {
            decimal dLatitude = ToRadians(latitudeVendor - latitudeCustomer);
            decimal dLongitude = ToRadians(longitudeVendor - longitudeCustomer);

            decimal lat1Rad = ToRadians(latitudeCustomer);
            decimal lat2Rad = ToRadians(latitudeVendor);

            decimal sinDLat = (decimal)Math.Sin((double)(dLatitude / 2));
            decimal sinDLon = (decimal)Math.Sin((double)(dLongitude / 2));

            decimal a = sinDLat * sinDLat + (decimal)Math.Cos((double)lat1Rad) * (decimal)Math.Cos((double)lat2Rad) * sinDLon * sinDLon;
            decimal c = 2m * (decimal)Math.Atan2((double)Math.Sqrt((double)a), (double)Math.Sqrt(1 - (double)a));

            decimal distance = EarthRadius * c;
            return distance;
        }

        // Fungsi untuk menghitung biaya pengiriman berdasarkan jarak
        public static decimal CalculateDeliveryCost(decimal latitude1, decimal longitude1, decimal latitude2, decimal longitude2)
        {
            decimal distance = CalculateDistance(latitude1, longitude1, latitude2, longitude2);
            return Math.Ceiling(distance / 100m) * CostPer100Km;
        }

    }
}
